Implement specification pattern
interactivereduction/IR-API pull request #277
Opened 2024-02-22 13:38 UTC by keiranjprice101

Closes # 

## Description

2024-02-22 13:39 UTC, keiranjprice101 commented on ir_api/core/specifications/reduction.py
> +# pylint: disable=unused-argument
See: https://github.com/interactivereduction/IR-API/pull/277/files#diff-c84d21f7021977eeefaca8726ed64293b40713a2ad0b5acfa6afc78fe7841072R64 for disable reason

2024-02-22 13:40 UTC, keiranjprice101 commented on ir_api/core/specifications/run.py
> +# pylint: disable=unused-argument
See: https://github.com/interactivereduction/IR-API/pull/277/files#diff-c84d21f7021977eeefaca8726ed64293b40713a2ad0b5acfa6afc78fe7841072R64
for disable reason

2024-02-27 09:27 UTC, Dagonite approved these changes
Looks good to me!

2024-02-29 10:16 UTC, keiranjprice101 commented
@Pasarus reready

2024-02-29 11:45 UTC, Pasarus requested changes
Just 2 small things

2024-02-29 13:59 UTC, Pasarus approved these changes

2024-02-29 13:59 UTC, merged